### ISSUE TITLE
Add paragraph or sentence for the context of the activity form.  

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#43]

**Comment by uladkasach** [comment]
![screenshot_2017-07-18_12-11-50](https://user-images.githubusercontent.com/10381896/28327727-4cc811e6-6bb2-11e7-80b4-8c095bd0ac7b.png)

**Comment by uladkasach** [comment]
![screenshot_2017-07-18_12-17-50](https://user-images.githubusercontent.com/10381896/28328020-2359a954-6bb3-11e7-9d91-3221a0296c85.png)
