### ISSUE TITLE
forms for diet need better context for week and day questions.  

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#46]
consider a high-er level heading to denote the per-week answers and the per-day answers.

**Comment by uladkasach** [comment]
![screenshot_2017-07-18_12-00-31](https://user-images.githubusercontent.com/10381896/28327193-b87eb5b8-6bb0-11e7-8c73-f680d9373001.png)

Potential solution.

**Comment by uladkasach** [comment]
![screenshot_2017-07-18_12-19-44](https://user-images.githubusercontent.com/10381896/28328108-66837ebc-6bb3-11e7-8cad-513e9ca67272.png)

**Comment by jennifershivers** [comment]
Not what I understood.  I understood that the first four selections are per week and the last two selections are per day.  I thought the intention was to have a heading over the first 4 that said per week and over the last two that said per day.  Can you re-look at the paper form closely and how those answers / columns are worded?

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/28331877-c7f8adfe-6bc0-11e7-8145-cd48eaeb0055.png)
