### ISSUE TITLE
add verbal example to the nutrition scale.  

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#55]
to make it easier to ideate on how the nutrition graph could be scaled, try showing some verbal labels that might drive us toward a decsion.  Maybe something like Meets or Exceeds recommendations, Meets recommendations, below recommendations, well below recommendations

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/28470043-67dc401e-6e06-11e7-982d-0560fba9c101.png)

Ideally, the labels would be located between ticks. A support question to the ChartJS team about how to do this has been asked here https://stackoverflow.com/questions/45240867/chartjs-place-y-axis-labels-between-ticks

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/28682267-37c703e6-72ca-11e7-9850-1bbbb00fcc33.png)
