### ISSUE TITLE
Nutrition advice additional requirements, (Guidelines)

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#58]
See email from 27 july with advice and thresholds 

Meat - is called protein 

Give eveyone a general reminder 
When they are at the threshold, procide additional advice 

Info is from choosemyplate.gov

---------
1. We could make a tabular design with Fruits, vegitables, protein and then the info from these advice 

2. Because the recommendations are based upon age and sex, can we give the recommendations tailored for them.  

3. Because the info is coming from the web site, make sure to credit it.  

4.  Could pictures or tips be included (use choosemyplate as reference for creativity) 

---------

**Comment by uladkasach** [comment]
Moving graph updates to a seperate issue, issue #62 : 

```
Graph - instead of having levels, have high and low - just to give indicators 
Have dotted line that goes across (high and low) 
"Needs work"  
"Good Choices"  
"Great Choices"  
Use the 11 and 22 thresholds as the line going across.  .
```

**Comment by uladkasach** [comment]
Guideline data from Dr. Haggstrom:
[nutrition_guidance.docx](https://github.com/personalcancertoolkit/openmrs-module-healthybehaviors/files/1277865/nutrition_guidance.docx)

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/30073047-5f01e6b2-923a-11e7-971f-aa711ec8ab72.png)
Almost done.
