### ISSUE TITLE
choosing people to compare to 

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#61]
1. invited to be a cancer buddy (add a third category  - healthy behavior) that you want to share) 
  - care givers or providers are not sharing data back  
2.  Then from those you have those that have selected to share, you can pick 1 to 5 to compare with.

**Comment by uladkasach** [comment]
Note, the ability to choose a cancer buddy and share data with them has to be seperatelly created in the personalcancertoolkit. However, you the selection of peers from a list is enabled. Additionally, an API enabling list manipulation (create, read - remove will need to be created in the future, all of this functionality is through simpleformservice) has been completed.
