### ISSUE TITLE
Graphs render blurry in iframe

### ISSUE THREAD

**Issue by uladkasach** [personalcancertoolkit/openmrs-module-healthybehaviors#64]
![image](https://user-images.githubusercontent.com/10381896/28793770-197953cc-7602-11e7-9754-463ca1869cdd.png)

Note, for some reason the screenshot is more clear than the actual display.

**Comment by uladkasach** [comment]
https://stackoverflow.com/questions/31910043/html5-canvas-drawimage-draws-image-blurry

**Comment by jennifershivers** [comment]
Can we close this one?  I havn't noticed this.

**Comment by uladkasach** [comment]
@jennifershivers  Closed. Maybe it was a fluke. I haven't been noticing it recently either.
