### ISSUE TITLE
create additional accounts with more time points for individual and friends

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#70]
To make it more clear what we actually have for the demo, create additional accounts with more time points for individual and friends

- an individual and at least two peers with 4 data points for each person
- record the data points outside of the time interval so that the button will be available

**Comment by uladkasach** [comment]
For Exercise:
![image](https://user-images.githubusercontent.com/10381896/30840732-eb5fa4d4-a246-11e7-985b-50b66d320380.png)

**Comment by uladkasach** [comment]
Nutrition:
![image](https://user-images.githubusercontent.com/10381896/30842147-3fecf0e0-a24e-11e7-9b91-dd837be658d8.png)
