### ISSUE TITLE
food graphing tables feedback (split in two different graphs)  

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#71]
Discussions 
- bar graphs might work better on individual graph 

Options discussed 
 -split the graph (one for fruits and one for meats) 
- more description of the directionality 

**decision** 
- split the graph into two different graphs 
- add the threshold

**Comment by uladkasach** [comment]
To discuss:
Here is a demo of a new graphing method for nutrition metrics. Here, both `fruits_and_veges` and `meats_and_snacks` are scored out of `[-1,1]` where they are positive if they are above their respective thresholds and negative below the threshold. 

![image](https://user-images.githubusercontent.com/10381896/30337141-614fbd6a-97b5-11e7-83b9-57a66eeebb7a.png)

**Comment by jennifershivers** [comment]
Resolved by changing graph labels and orientation.
