### ISSUE TITLE
On the exercise graph there looks like there was text type over on the date label.  

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#82]

**Comment by uladkasach** [comment]
Before:
![image](https://user-images.githubusercontent.com/10381896/30973092-43a26420-a43a-11e7-805d-847dfb2a091f.png)
After:
![image](https://user-images.githubusercontent.com/10381896/30973120-5356e79c-a43a-11e7-9780-19dc58a3357d.png)

**Comment by jennifershivers** [comment]
:-)
