### ISSUE TITLE
graphing grid 

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-healthybehaviors#83]
the two graphs currently have different grids.  Change the grids to both be like the exercise graph.  
Currently there is a difference because of the calculations.  

Burke - Dots don't have to be on the line.  Lining the labels with the lines helps.  No need for the zero line between "good choices" and "needs work"

**Comment by uladkasach** [comment]
![image](https://user-images.githubusercontent.com/10381896/30972800-9d8eaef4-a439-11e7-8529-074cca0a04e5.png)

**Comment by jennifershivers** [comment]
You seem to still be having issues with the legend at the bottom and overlapping text.  Maybe don't print "today's date" on the graph????
